<?php
/**
 * Shared helpers for auto-creating login accounts, used by
 * admin/lecturers.php, admin/lecturers_import.php, admin/students.php,
 * admin/students_import.php, head_academic/lecturers.php, and
 * admin/users.php.
 */
declare(strict_types=1);

/**
 * Find a column index in an Excel/CSV import header row by trying a list of
 * accepted header strings (English + Somali synonyms), in order. $headerRow
 * must already be lowercased and trimmed (as produced by
 * mb_strtolower(trim(...)) over the raw header cells).
 */
function find_import_column(array $headerRow, array $candidates): int|false
{
    foreach ($candidates as $candidate) {
        $index = array_search($candidate, $headerRow, true);
        if ($index !== false) {
            return $index;
        }
    }

    return false;
}

/**
 * Base slug for a name-derived username: the person's own given name (the
 * first word of their full name), lowercase, alphanumeric only. Somali names
 * are Given + Father + Grandfather, not Given + Surname, so later words
 * identify lineage rather than the person — only the first word is used.
 */
function name_username_base(string $fullName, string $fallback): string
{
    $parts = array_values(array_filter(preg_split('/\s+/', trim($fullName)), static fn ($p) => $p !== ''));
    $first = $parts[0] ?? '';
    $base = strtolower((string) preg_replace('/[^a-zA-Z0-9]/', '', $first));

    return $base !== '' ? $base : $fallback;
}

/**
 * Last N characters of an admin-entered student_no/staff_no, used to make
 * name-based usernames unique-by-construction without relying purely on a
 * collision counter. IDs are free-form (assigned by the registration office
 * / HR, not generated by this system), so this prefers digits (e.g. "07"
 * from "1472/23") but falls back to trailing alphanumeric characters for
 * IDs with no digits at all.
 */
function id_sequence_suffix(string $idNo, int $digits = 2): string
{
    $digitsOnly = preg_replace('/\D/', '', $idNo);
    if ($digitsOnly !== '') {
        return substr($digitsOnly, -$digits);
    }

    $alnum = strtolower((string) preg_replace('/[^a-zA-Z0-9]/', '', $idNo));

    return substr($alnum, -$digits);
}

function lecturer_username_exists(mysqli $conn, string $username): bool
{
    $stmt = $conn->prepare('SELECT id FROM users WHERE username = ?');
    $stmt->bind_param('s', $username);
    $stmt->execute();
    $exists = (bool) $stmt->get_result()->fetch_assoc();
    $stmt->close();

    return $exists;
}

/**
 * Build a username for a lecturer: name slug + last 2 digits of their
 * staff_no sequence (e.g. "acali07"). Falls back to an incrementing suffix
 * in the rare case that combination is already taken.
 */
function generate_lecturer_username(mysqli $conn, string $fullName, string $staffNo): string
{
    $base = name_username_base($fullName, 'lecturer') . id_sequence_suffix($staffNo);

    $username = $base;
    $suffix = 1;
    while (lecturer_username_exists($conn, $username)) {
        $username = $base . $suffix;
        $suffix++;
    }

    return $username;
}

/**
 * Build a username for a student: name slug + last 2 digits of their
 * student_no sequence (e.g. "ahmedcali07"). Falls back to an incrementing
 * suffix in the rare case that combination is already taken.
 */
function generate_student_username(mysqli $conn, string $fullName, string $studentNo): string
{
    $base = name_username_base($fullName, 'student') . id_sequence_suffix($studentNo);

    $username = $base;
    $suffix = 1;
    while (lecturer_username_exists($conn, $username)) {
        $username = $base . $suffix;
        $suffix++;
    }

    return $username;
}

/**
 * Build a unique username for a general admin-appointed account — Dean, Head
 * of Academic Affairs, Registration Office — using the same name-slug base,
 * with an incrementing suffix on collision (these accounts have no
 * student_no/staff_no-style ID to derive a suffix from).
 */
function generate_admin_username(mysqli $conn, string $fullName): string
{
    $base = name_username_base($fullName, 'staff');

    $username = $base;
    $suffix = 1;
    while (lecturer_username_exists($conn, $username)) {
        $username = $base . $suffix;
        $suffix++;
    }

    return $username;
}

/**
 * Generate a random temporary password containing at least one uppercase
 * letter, one lowercase letter, one digit, and one symbol. Still used for
 * admin-appointed accounts (Dean, Head of Academic Affairs, Registration
 * Office) which have no student_no/staff_no-style ID to use as a password.
 */
function generate_temp_password(): string
{
    $upper = 'ABCDEFGHJKLMNPQRSTUVWXYZ';
    $lower = 'abcdefghijkmnopqrstuvwxyz';
    $digits = '23456789';
    $symbols = '!@#$%*?';
    $all = $upper . $lower . $digits . $symbols;

    $password = [
        $upper[random_int(0, strlen($upper) - 1)],
        $lower[random_int(0, strlen($lower) - 1)],
        $digits[random_int(0, strlen($digits) - 1)],
        $symbols[random_int(0, strlen($symbols) - 1)],
    ];

    for ($i = 0; $i < 6; $i++) {
        $password[] = $all[random_int(0, strlen($all) - 1)];
    }

    shuffle($password);

    return implode('', $password);
}
